### ISSUE TITLE
db- update mentors list

### ISSUE THREAD

**Issue by fishcodeslol** [summonerschool/SSMentorRequest#3]
Public Mentors list needs an update. There are people who current mentors that are missing on the list, and some mentors are still displaying old discord discriminators (are we keeping #0 to differentiate between usernames?)

**Comment by LordZesus** [comment]
The issues for these currently are

> Currently mentors that are missing on the list
This is purely due to either mentors not having signed up to the website or not currently enabled at the moment, this is a logistical issue, not technical one

> Some mentors are displaying old discord ID / old discriminator / not updated
This is actually being worked on currently, no need to change at the moment.

**Comment by LordZesus** [comment]
> Keep the #0 or no?

The new usernames should actually have the `@[username]` format I think. The users now have `username` field for their discord handle and `global_name` for their cosmetic name, so probably just go with the `username` only
