### ISSUE TITLE
UI - /admin/apps improvements

### ISSUE THREAD

**Issue by fishcodeslol** [summonerschool/SSMentorRequest#4]
Original comment: 

> Add a new sort icon and a button or something to allow all new mentor applications to be collapse/expandable

- [X] Add comments for applications
- [X] Add ability to view who voted on apps
- [x] Add tooltip and/or confirmation modal telling the user exactly what's going to happen when they press the button
- [x] General UI cleanup
- [x] Add Trial tab for mentor currently under trial
- [x] Add trial process information for apps under trial

**Comment by LordZesus** [comment]
Mentor applications are currently already collapsible. You can do so by clicking on the main row of the table. 
However having a button for that is likely much better idea, or perhaps even a collapsing component could be good (How you can fit that in a table is beyond me, I have attempted this precisely once before)

Sort icons / functions would certainly be good, look to lift the functions from the requests sheet, if it'll be useful

**Comment by fishcodeslol** [comment]
> 

Ah this one is a change to include a "Collapse all" because the default is a "Show all." When I was reviewing mentor apps it was hard to see which ones I already voted on because they were all open by default.

**Comment by LordZesus** [comment]
I suppose the solution should be collapse all applications that has been voted on by the reviewer, since the reviewer really should just vote on all requests anyway. Adding this to the current To-Do

**Comment by LordZesus** [comment]
Upon further inspection I probably should clean up the code first before you add the buttons for better UI, hold onto this for now

**Comment by fishcodeslol** [comment]
> I suppose the solution should be collapse all applications that has been voted on by the reviewer, since the reviewer really should just vote on all requests anyway. 

Yea, this sounds like a good idea. I'll hold off for now until you ping again. Maybe tag me after you do the cleanup and reference this Github issue?
